### ISSUE TITLE
Создание новой задачи

### ISSUE THREAD

**Issue by VADZILko** [southbridgeio/redmine_2chat#13]
Используем плагины redmine_bots + redmine_intouch + redmine_2chat

Redmine 3.4.6
Sidekiq 5.2.1
Ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]

Авторизация у бота прошла. На команды отвечает, кроме одной: /new
В sidekiq в "попытки" пишет:
+ Очередь
`IssueChatMessageSenderWorker`

+ Аргументы
`<supersecretTelegramID>, "telegram", "Выберите или введите название проекта. Страница 1.", {"reply_markup"=>"#<Telegram::Bot::Types::ReplyKeyboardMarkup:0x00000003637f10>"}368430771, "telegram", "Выберите или введите название проекта. Страница 1.", {"reply_markup"=>"#<Telegram::Bot::Types::ReplyKeyboardMarkup:0x00000003637f10>"}`

+ Ошибка
`Telegram::Bot::Exceptions::ResponseError: Telegram API has returned the error. (ok: "false", error_code: "400", description: "Bad Request: can't parse reply keyboard markup JSON object")`

+ Очередь 
`issue_chats`

Вроде все делал по инструкциям. Что мог забыть/не сделать/прошляпить?

PS: до этого пользовались старыми версиями ваших плагинов redmine_chat_telegram и redmine_intouch. Перед обновлением удалил старые плугины (включая redmine_telegram_common). После установил новые используя `git clone`. 

ЗЫЫ: По факту, не отображается "west_cost_customs" клавиатура при создании задачи.
Если вводить точные названия проекта,кому назначать и т.д. то задача создается

**Comment by VADZILko** [comment]
По факту, не отображается "west_cost_customs" клавиатура при создании задачи.
Если вводить точные названия проекта,кому назначать и т.д. то задача создается

**Comment by funk-yourself** [comment]
Должно быть исправлено в текущей версии. Напишите, пожалуйста, если проблема проявится снова.
