### ISSUE TITLE
Issues chats stack in queues

### ISSUE THREAD

**Issue by amarkstar** [southbridgeio/redmine_2chat#22]
Environment:
  Redmine version           4.0.3.stable
  Ruby version                 2.3.3-p222 (2016-11-21) [x86_64-linux]
  Rails version                  5.2.2.1
  Environment                 development
  Sidekiq                          5.2.7
  running bundle exec rake redmine_bots:telegram

commands in redmine_bot can be process (e.g. /connect) but redmine_2chat reply stack in queues.

e.g:
1. user send /me from Telegram
2. Incoming queue to telegram 
3. Redmine processed and reply queue to issue_chats job IssueChatMessageSenderWorker

![image](https://user-images.githubusercontent.com/771823/57179955-28419280-6eb6-11e9-8c49-7d1f6e584344.png)

Is it i'm missing anything?

**Comment by joseluiscampos** [comment]
Hi,

Check if you have sidekiq running.

`ps -ef | grep sidekiq`

If not, turn it on: 

`bundle exec sidekiq -e production`

Best Regards

**Comment by hawatius** [comment]
I have exactly such a problem, is there a solution?

**Comment by Luckyvb** [comment]
it resolved by:
`bundle exec sidekiq -q telegram -e production -r /opt/redmine/`

-d is depricated
why its not start automitic or how demonize it ?

**Comment by Luckyvb** [comment]
https://github.com/mperham/sidekiq/blob/master/examples/systemd/sidekiq.service

`Type=simple #if sidekiq version< 6`

if using rvm
```
ExecStart= /usr/local/rvm/gems/ruby-2.6.6/wrappers/bundle exec sidekiq -e production -C config/sidekiq.yml -L log/sidekiq.log
```

#sample for config/sidekiq.yml
https://github.com/mperham/sidekiq/blob/master/examples/config.yml
need 3 queue:
```
:queues:
- default
- telegram
- issue_chats
```
