### ISSUE TITLE
Create chat - error

### ISSUE THREAD

**Issue by kukara4** [southbridgeio/redmine_2chat#25]
Добрый! Получаю следующую ошибку при создании чата с тикета: 

E, [2020-02-08T23:01:21.499619 #1492] ERROR -- : GLOBAL NoMethodError: undefined method `shared_url' for nil:NilClass
/opt/redmine/redmine-4.1.0/plugins/redmine_2chat/lib/redmine2chat/telegram/commands/new_issue_command.rb:104:in `create_chat'
/opt/redmine/redmine-4.1.0/plugins/redmine_2chat/lib/redmine2chat/telegram/commands/new_issue_command.rb:84:in `execute_step_6'
/opt/redmine/redmine-4.1.0/plugins/redmine_2chat/lib/redmine2chat/telegram/commands/new_issue_command.rb:16:in `execute_step'
/opt/redmine/redmine-4.1.0/plugins/redmine_2chat/lib/redmine2chat/telegram/commands/new_issue_command.rb:10:in `execute'

**Comment by funk-yourself** [comment]
Добрый день! Если ещё актуально, попробуйте пожалуйста последнюю версию плагина. Понадобится также обновление плагина redmine_bots и библиотеки tdlib. Если ещё будут вопросы, можете переоткрыть issue.
